### ISSUE TITLE
Failed to refresh session是token过期了吗？

### ISSUE THREAD

**Issue by JoeyTrue** [bupticybee/ChineseAiDungeonChatGPT#38]
Traceback (most recent call last):
  File "F:\python3.9.7\lib\site-packages\revChatGPT\ChatGPT.py", line 230, in refresh_session
    raise Exception(f'Response code: {response.status_code} \n Response: {response.text}')
Exception: Response code: 200 
 Response: {}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\browser_download\ChineseAiDungeonChatGPT-0.2.0\app.py", line 164, in <module>
    story_teller = StoryTeller(config, story_background)
  File "E:\browser_download\ChineseAiDungeonChatGPT-0.2.0\story.py", line 10, in __init__
    self.chatbot = Chatbot(config, conversation_id=None)
  File "F:\python3.9.7\lib\site-packages\revChatGPT\ChatGPT.py", line 81, in __init__
    self.retry_refresh()
  File "F:\python3.9.7\lib\site-packages\revChatGPT\ChatGPT.py", line 92, in retry_refresh
    raise exc
  File "F:\python3.9.7\lib\site-packages\revChatGPT\ChatGPT.py", line 88, in retry_refresh
    self.refresh_session()
  File "F:\python3.9.7\lib\site-packages\revChatGPT\ChatGPT.py", line 245, in refresh_session
    raise Exception("Failed to refresh session!") from exc
Exception: Failed to refresh session!

**Comment by bupticybee** [comment]
是的，openai对接口做了很多限制
