### ISSUE TITLE
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'

### ISSUE THREAD

**Issue by eastyy** [bupticybee/ChineseAiDungeonChatGPT#40]
Traceback (most recent call last):
  File "/Users/yy/ChineseAiDungeonChatGPT/app.py", line 8, in <module>
    from story import StoryTeller
  File "/Users/yy/ChineseAiDungeonChatGPT/story.py", line 1, in <module>
    from revChatGPT.revChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'

你好，请问这个问题应该怎么解决？

**Comment by bupticybee** [comment]
参考 #39
