### ISSUE TITLE
使用官方api接口出错

### ISSUE THREAD

**Issue by GUNNEO** [bupticybee/ChineseAiDungeonChatGPT#53]
Traceback (most recent call last):
  File "/Users/gunneo/Codes/AI/ChineseAiDungeonChatGPT-main/example_story.py", line 7, in <module>
    chatter.start_cli()
  File "/Users/gunneo/Codes/AI/ChineseAiDungeonChatGPT-main/story_rewrite.py", line 125, in start_cli
    self.setup_chatbot()
  File "/Users/gunneo/Codes/AI/ChineseAiDungeonChatGPT-main/story_rewrite.py", line 91, in setup_chatbot
    self.login(self.config)
  File "/Users/gunneo/Codes/AI/ChineseAiDungeonChatGPT-main/story_rewrite.py", line 38, in login
    self.chatbot = ofChatbot(api_key=_config['api_key'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gunneo/anaconda3/lib/python3.11/site-packages/revChatGPT/V3.py", line 108, in __init__
    self.aclient = httpx.AsyncClient(
                   ^^^^^^^^^^^^^^^^^^
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'follow_redirects'

**Comment by bupticybee** [comment]
接口问题的话应该查一下revChatGPT 文档，这个项目只有40多行，没什么复杂逻辑的
