### ISSUE TITLE
好像不行了

### ISSUE THREAD

**Issue by floodsung** [bupticybee/ChineseAiDungeonChatGPT#6]
Traceback (most recent call last):
  File "/Users/floodsung/Documents/ChatGPT_new/src/revChatGPT/revChatGPT.py", line 62, in get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_story.py", line 8, in <module>
    story_teller.interactive()
  File "/Users/floodsung/Documents/ChineseAiDungeonChatGPT/story.py", line 37, in interactive
    self.action(action)
  File "/Users/floodsung/Documents/ChineseAiDungeonChatGPT/story.py", line 30, in action
    resp = self.chatbot.get_chat_response(prompt)  # Sends a request to the API and returns the response by OpenAI
  File "/Users/floodsung/Documents/ChatGPT_new/src/revChatGPT/revChatGPT.py", line 86, in get_chat_response
    return self.get_chat_text(data)
  File "/Users/floodsung/Documents/ChatGPT_new/src/revChatGPT/revChatGPT.py", line 66, in get_chat_text
    raise ValueError("Response is not in the correct format")
ValueError: Response is not in the correct format

**Comment by bupticybee** [comment]
在具体报错是：

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0z7mOYwAAAADmtQZsK4jTSqp7uFyqad3+U0lOMzBFREdFMDIxMwBlNjZiOGIwMy0wNzkzLTQ0MDktOTc3My0yZTYxMmU3MWExZTM=</span></div></div></body></html>
Traceback (most recent call last):
  File "/Users/bytedance/PycharmProjects/ChineseAiDungeonChatGPT/venv/lib/python3.6/site-packages/revChatGPT/revChatGPT.py", line 61, in get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of rang



我hightlight一下： We're working to restore all services as soon as possible. Please check back soon.

openai的服务器挂了，等一会就好了，昨天也挂了好几次，现在这个chatgpt太火了

**Comment by bupticybee** [comment]
BTW， 我是fuming haha

**Comment by bupticybee** [comment]
<img width="1009" alt="截屏2022-12-06 上午11 44 58" src="https://user-images.githubusercontent.com/9393610/205807843-8e5460d7-5ef8-438f-bc1e-534fd3709738.png">

刚才openai的chatgpt的页面也挂了，可能得等一下

**Comment by bupticybee** [comment]
现在openai已经修复了服务器，可以重新尝试下

**Comment by floodsung** [comment]
哈哈哈

**Comment by floodsung** [comment]
怎么加个wechat?可以发我邮箱floodsung@gmail.com
